version: "2"
services:
  app:
    container_name: jessicapaola/jobpositions
    restart: always
    build: .
    ports:
      - "8080:8080"
    links:
      - mongo
  mongo:
    container_name: graphqlmongo
    image: mongo
    volumes:
      - .:/usr/app
    ports:
      - "27017:27017"
  admin-mongo:
    image: 0x59/admin-mongo:latest
    ports:
      - "8082:8082"
    environment:
      - PORT=8082
      - CONN_NAME=mongo
      - DB_HOST=mongo
    links:
      - mongo